# Generated by Django 5.0.6 on 2024-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True #it means that this migration is very first in our project

    dependencies = [ #because it's the very first it has no dependencies
    ]

    operations = [
        migrations.CreateModel(
            name='Post', #it does not create the "Post" model class, it means that it specifies it
            fields=[ #and this means these fields will be added to the "Post" model
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('slug', models.SlugField()), #slug is like the text but contains slashes and hyphens because it needs to be used for urls
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

#this whole file is designed to update our whole database for the Post model by creating a new table