# Generated by Django 5.0.6 on 2024-07-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'), #it means this migration depends on our first one
    ]

    operations = [
        migrations.AddField(
            model_name='post', #it specifies what model name will be modified, so does the "name" param. And it refers to the database model name, that's why it's in lowercase
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''), #this field will be added to our current table
        ),
    ]

#this is the second migration, and it modifies our first migration