# Generated by Django 5.0.6 on 2024-07-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ #this migration depends on our first
        ('posts', '0001_initial'),
    ]

    operations = [ #this migration adds more fields to our current one
        migrations.AddField(
            model_name='post', #this the name of our model. This is the same as "Post". We use lowercase when we're updating and uppercase when we create
            name='banner', #this the name of our new field
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
